### ISSUE TITLE
Image Resources in Project Root

### ISSUE THREAD

**Issue by jordanwillis** [mshamara/ColmarAcademy#1]
Nice work so far on what I have reviewed!  As I was reviewing the project, the first ting that jumped out at me was all the image files in the root of your project folder.  After taking a bit close look it looks like you might have put in some extra effort to enable your web site to be installed as a progressive web app.  Nice work!

My only recommendation would be to move all the icon asset files into separate folder so that it does not clutter up your root folder.  This will make the project a bit cleaner but will also require having to update the icon paths in the manifest file.

**Comment by mshamara** [comment]
Hi Jordan! 
I thought too that the files in the root seems messy, but I understood the quides on how to get the favicon as they should be directly on the root :D I didn't have time to investigate more, so I just added them there...Have to get more info on that subject =)
