### ISSUE TITLE
Closing nav tag and other validation items

### ISSUE THREAD

**Issue by jordanwillis** [mshamara/ColmarAcademy#2]
Your HTML looks really good, nice job!  One issue that I stumbled upon when performing the review is that your mobile nav element is not properly closed.

https://github.com/mshamara/ColmarAcademy/blob/master/index.html#L33

Fortunately, modern browsers these days are pretty lenient about these sorts of things and are able to detect where the closing tag should be.  One way that you can guard against mistakes like this is by running your page through a validator just to make sure all is well.  As a bonus these validators also provide nice hints/tips that you may not have even considered.  In fact, I just ran the page through this validator so that I could send you an example.

https://validator.w3.org/nu/?doc=https%3A%2F%2Frawgit.com%2Fmshamara%2FColmarAcademy%2Fmaster%2Findex.html

It turns out there are many other unclosed elements and related items for you to take a look at.

**Comment by mshamara** [comment]
Oh dear! I used the validator after I finished the base structure, but have to remember to use it also before finishing. Thank you for the hint!
