### ISSUE TITLE
Summary: Grade = Meets Expectations

### ISSUE THREAD

**Issue by jordanwillis** [mshamara/ColmarAcademy#3]
Overall you did a great job on this project!  You did everything well from nicely formatted HTML/CSS, working responsive layout with media queries that optimizes the page for desktop/mobile, and adding your own styling flair to the site.  It was nicely done!

I think the primary feedback is just watch out for typos in your HTML with especially around unclosed elements and related structural issues.  With the help of a good validator this is one easy thing to resolve without too much effort.

Keep up the good work!

**Comment by mshamara** [comment]
Thank you! This was a nice challenge! =)
